### PR TITLE
Adding Hearthstone Top Decks Information

### PR DESCRIPTION
**Pull request by evident**
Swapped out Hearthhead for HSTD
Changed all token IDs for HSTD ones

### CODE REVIEW

**Comment by d-schmidt** [comment]
Do the tests still complete successfully?
https://github.com/d-schmidt/hearthscan-bot/pull/1/commits/8da9a21cf6119e64ab2374ed88d8269fff3e8c56#diff-b284a28710cce90d9d9be3a7f4cabc8eL298 covering https://github.com/d-schmidt/hearthscan-bot/pull/1/commits/8da9a21cf6119e64ab2374ed88d8269fff3e8c56#diff-702b6abf015bfdb4e41308ddd3b297a9R26 looks like it will fail.

**Comment by evident** [comment]
I wasn't able to test it, I tried installing python and praw but it wasn't working correctly. I'll give it another go. I looked at the links you mentioned, but I'm not sure what you mean by them "covering" certain things. I apologize, I'm not familiar with Python.

**Comment by d-schmidt** [comment]
Tests covering something is not Python specific: https://en.wikipedia.org/wiki/Code_coverage

To run the tests you need more than praw. The readme hopefully contains everything: https://github.com/d-schmidt/hearthscan-bot/blob/master/README.md

**Comment by d-schmidt** [comment]
I guess you gave up? Please submit a new request.

**Pull request closed without merging**
